//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Test.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;

    public partial class Ingridients
    {
        [Key]
        public int Ingridient_Id { get; set; }
        public string IngridientName { get; set; }
        public Nullable<int> Receipt_Id { get; set; }
        public string Quantity { get; set; }
    
        public virtual Receipts Receipts { get; set; }
    }
}
