//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System.ComponentModel.DataAnnotations;

namespace Test.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Receipts
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Receipts()
        {
            this.Dishes = new HashSet<Dishes>();
        }
        [Key]
        public int Receipt_Id { get; set; }
        public string ReceiptName { get; set; }
        public Nullable<int> Ingridient_Id { get; set; }
        public Nullable<int> Ingridient_Quantity { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Dishes> Dishes { get; set; }
        public virtual Ingridients Ingridients { get; set; }
    }
}
